[tool.poetry]
name = "arcaflow-plugin-rtla"
version = "0.1.0"
description = ""
authors = ["Arcalot"]
license = "Apache-2.0+GPL-2.0-only"

packages = [
   { include="rtla_plugin.py", from="./arcaflow_plugin_rtla"  },
]

[tool.poetry.dependencies]
python = "^3.9"
arcaflow-plugin-sdk = "^0.14.3"

[tool.poetry.dev-dependencies]
docformatter = "1.7.5"
autoflake = "2.3.1"
pydocstyle = "6.3.0"
black = "24.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
